//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChordManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Chord
    {
        public long Id { get; set; }
        public string Chord_Name { get; set; }
        public string Note_1 { get; set; }
        public string Note_2 { get; set; }
        public string Note_3 { get; set; }
        public Nullable<bool> Is_Valid { get; set; }
    }
}
